#!/bin/bash

# dmusick_path / History
cachedir="/tmp/"
cache="$cachedir/dmusick"

[ ! -e "$cachedir" ] && mkdir -p "$cachedir"
[ ! -e "$cache" ] && touch "$cache"


if [ ! -s "$cache" ]; then
        FNORD=`echo | dmenu "$@" -p ♫`
else
        FNORD=`sort $cache | uniq | dmenu "$@" -p ♫`
fi

echo "$FNORD" >> $cache
youtube-dl --rm-cache-dir -o - -q "ytsearch: $FNORD" | mpv --quiet --really-quiet - & disown



